version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thiqah-container-mvc_asp_identity
    ports:
      - "8083:80" 
    depends_on:
      - db

  db:
    image: "microsoft/mssql-server-linux"
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Aa123456"
      ACCEPT_EULA: "Y"

    volumes:
      - sql-datavolume:/var/opt/mssql
volumes:
  sql-datavolume:
